### ISSUE TITLE
Swift 2 Sample App?

### ISSUE THREAD

**Issue by damianesteban** [p2/OAuth2PodApp#1]
Well I was going to make a Swift 2 Sample App, but I'm having problems installing the swift 2 pod.  It is giving me the following error:

`Use of unresolved identifier 'ArchiveKey'`
`Use of unresolved identifier 'Keychain'`

**Comment by p2** [comment]
I'm not much of a CocoaPods user, do I have to publish the swift 2.0 branch of OAuth2 to CocoaPods?

The error you see is because you seem to not have checked out the `Keychain` submodule. Do that with `git submodule update --init`.

**Comment by damianesteban** [comment]
Sorry, I should have made the issue more clear.

I am able to install the pod just fine, but then when I attempt to build the application with the pod I get the errors:

`Use of unresolved identifier 'ArchiveKey'`
`Use of unresolved identifier 'Keychain'`

I think I may just forgo the use of cocoapods and add the library as a git submodule altogether.

**Comment by p2** [comment]
These are classes contained in the submodule, so it seems those have not been added correctly with your pod installation. Make sure you have the :submodules flag set correctly.

**Comment by damianesteban** [comment]
That did the trick!  Thank you very much.  Cocoapods have been giving me a lot of headaches lately and I'm thinking of using Carthage, or just plain old git submodules.

Anyway, I was planning on making a Swift 2 Example App using `SFSafariViewController` to familiarize myself with OAuth for an iOS9 project I'm working on, I'll submit a PR when I'm done with it if you would like.

**Comment by p2** [comment]
Sure, cool, I haven't used the new safari view controller yet.
