### ISSUE TITLE
Can't run in Xcode8 with Swift 3.0

### ISSUE THREAD

**Issue by tesths** [p2/OAuth2PodApp#2]
I clone this project. When I run the project, Xcode alert me it need to be convert😔

**Comment by p2** [comment]
Pull latest, run `pod update`, maybe `pod cache clean p2.OAuth2` first, then Hit <key>CMD</key> <key>Shift</key> <key>K</key> to clean the target, and try again.

**Comment by tesths** [comment]
![image](https://cloud.githubusercontent.com/assets/8736805/18812020/b796e6c6-82f8-11e6-832c-a608c4b33b3c.png)
It can't run.
I think the Alamofire is not the right version.

**Comment by p2** [comment]
Did you `git pull`? Did you `pod cache clean p2.OAuth2`? Did you Shift + CMD + K?

I needed to do all these things, then it worked.

**Comment by tesths** [comment]
Oh! I find the problem! 
Alamofire 4.0 need cocoapods 1.1.0, it's the pre version. I use cocoapods 1.0.1.
Just now, I update my cocoapods. And it's run!
Thank you! I will close this issue!

**Comment by p2** [comment]
Great, thanks for checking back!
