### ISSUE TITLE
Forget Tokens does not properly logout

### ISSUE THREAD

**Issue by davidvirdeforshh** [p2/OAuth2PodApp#5]
Steps to reproduce:
1. Click "Sign in (Embeded)" and authorize.
2. Click "Forget Tokens"
3. Click "Sign in (Embeded)"
Expected: Promted for username and password
Actual: Browsers quickly opens, then closes and returns to app in a logged in state showing profile picture.

Tested on ios iPhone X.

**Comment by p2** [comment]
Yes, that’s because of session persistence. Please see [README, part 9. Logout](https://github.com/p2/OAuth2).

**Comment by davidvirdeforshh** [comment]
So either remove the button "Forget Tokens" or implement a full logout example.
Having a button in an example app that in practice does nothing is just confusing.

**Comment by p2** [comment]
Depends, not all websites keep sessions for OAuth logins, so on some services you’re always prompted to log in. On some you can use the `rel=login` auth URL param to achieve that.

This button does exactly what it should do and is there for testing purposes.
